Add RPCService
FAForever/kotlin-ice-adapter pull request #8
Opened 2023-09-08 22:12 UTC by BlackYps

closes #4 

At the moment the rpcService is not used yet

2023-09-12 13:06 UTC, Brutus5000 requested changes

2023-09-12 13:06 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCHandler.kt
> +    }
Pass the objectMapper via constructor. We shouldn't use 2 different objectMappers when they are both for the same RPC connection.

2023-09-12 13:06 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCService.kt
> +    }
```suggestion
    private val objectMapper = ObjectMapper().apply {
      registerModule(JavaTimeModule())
    }
    private val rpcHandler: RPCHandler = RPCHandler(iceAdapter, objectMapper)
    private val tcpServer: TcpServer = TcpServer(rpcPort, rpcHandler)

    @Volatile
    private var skipRPCMessages = false
```

2023-09-12 13:06 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCService.kt
> +class RPCService(
I'd prefer RpcService (otherwise it would need to be ICEAdapter, which is also kind of annoying)

2023-09-12 13:06 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCHandler.kt
> +class RPCHandler(
I'd prefer RpcHandler (otherwise it would need to be ICEAdapter, which is also kind of annoying)

2023-09-12 13:06 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCService.kt
> +                iceAdapter.stop()
```suggestion
                logger.info { "Lost connection to first RPC Peer, stopping adapter..." }
                iceAdapter.stop()
```

2023-09-12 13:06 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCService.kt
> +    private val objectMapper = ObjectMapper()
```suggestion
    private val objectMapper: ObjectMapper = ObjectMapper()
```

2023-09-12 13:06 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCService.kt
> +    private var skipRPCMessages = false
Do we really want to use this? I'm still not sure what the point is here. If the Rpc connection breaks can/should the game continue?

2023-09-12 13:06 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCService.kt
> +        }
```suggestion
        get() = try {
               tcpServer.firstPeer.get()
            } catch (e: Exception) {
                logger.error(e) { "Error on fetching first peer" }
                null
            }
```

2023-09-12 13:06 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCService.kt
> +            }
We're not in Java, we don't need to wrap checked exceptions in runtime exceptions

2023-09-25 12:40 UTC, BlackYps commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCHandler.kt
> +    }
what exactly does the objectmapper do anyway?

2023-09-25 12:44 UTC, BlackYps commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCService.kt
> +    private var skipRPCMessages = false
I have no idea. I was just reimplementing the java version. I also don't know what the reasoning is behind not stopping the adapter if and only if the game is launching at that moment. Maybe Geosearchef remembers

2023-09-25 13:05 UTC, BlackYps commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCService.kt
> +            }
so I just get rid of the whole try/catch block?

2023-09-25 21:38 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCService.kt
> +            }
correct

2023-09-25 21:38 UTC, Brutus5000 commented on kia-cli/src/main/kotlin/com/faforever/ice/rpc/RPCHandler.kt
> +    }
Maps objects to JSON and vice versa

2023-09-28 19:22 UTC, BlackYps commented
Not all of the callbacks are implemented. And I am not 100% that the ones that are, are called at the right place. The structure of the kotlin and the java adapter is different, so I could not always track it down.

2023-09-28 21:21 UTC, Brutus5000 commented
WTF happened with the rebase O_o

2023-09-29 19:56 UTC, merged